// Sélectionnez l'élément conteneur de la table de Gantt
const ganttContainer = document.getElementById('gantt-container');

// Créez un élément de tableau pour la table de Gantt avec un attribut id
const table = document.createElement('table');
table.classList.add('gantt-table');
table.id = 'gantt-prompt-phaze'; // Ajoutez un ID à la table

// Créez l'en-tête de la table
const thead = document.createElement('thead');
const headerRow = document.createElement('tr');
// Créez des en-têtes de colonne ici, par exemple :
const headers = ['id', 'Phase', 'titre', 'meta-decription', 'Start Date', 'duration', 'End Date', 'Progress', 'promptModel', 'promptNeofs', 'promptZira', 'currentStep', 'step1', 'step2', 'step3', 'step4', 'step5', 'api-rest', 'hash', 'url'];
headers.forEach((headerText) => {
  const th = document.createElement('th');
  th.textContent = headerText;
  headerRow.appendChild(th);
});
thead.appendChild(headerRow);

// Créez le corps de la table
const tbody = document.createElement('tbody');
// Créez des lignes de tâches ici, par exemple :
const tasks = [
  {
    id: '1',
    phase: 'PHASE 1',
    titre: 'id-conception',
    metaDescription: 'test',
    startDate: '2024-01-15',
    duration:'5m',
    endDate: '2024-01-30',
    progress: '50%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep: 'update',
    step1:'3%',
    step2:'10%',
    step3: 'x',
    step4: 'x',
    step5: 'x',
    apiRrest: 'email',
    hash: '97365782323289846',
    url: "tag", 
  },
  {
    id: '1-1-2',
    phase: '1-1-2',
    titre: 'id-mission',
    metaDescription: 'mission prompt gann',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep: 'update',
    step1:'3%',
    step2:'10%',
    step3: 'x',
    step4: 'x',
    step5: 'x',
    apiRrest: 'email',
    hash: '97342692343293249',
    url: 'tag',
  },
  {
    id: '1-1-3',
    phase: '1-1-3',
    titre: 'id-Objectif',
    metaDescription: 'objectif devops full stack',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: 'x',
    step5: 'x',
    apiRrest: 'email',
    hash: '979789169532323',
    url: 'tag',
  },
  {
    id: '2-0-0',
    phase: 'PHASE2',
    titre: 'id-Configuration',
    metaDescription: 'config',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'x',
    step2:'x',
    step3: '2%',
    step4: '3%',
    step5: 'x',
    apiRrest: 'email',
    hash: '979789169997032',
    url: 'tag',
  },
  {
    id: '2-0-1',
    phase: '2-0-1',
    titre: 'id-Configuration',
    metaDescription: 'config',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9797891699703',
    url: 'tag',
  },
  {
    id: '2-1-1',
    phase: '2-1-1',
    titre: 'id-Configuration',
    metaDescription: 'config',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9797891699743272',
    url: 'tag',
  },
  {
    id: '2-1-1',
    phase: 'PHASE 3',
    titre: 'id-setup',
    metaDescription: 'config',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9797891699743272',
    url: 'tag',
  },
  {
    id: '3-0-1',
    phase: '3-0-1',
    titre: 'dataset',
    metaDescription: 'config',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9797891699743272',
    url: 'tag',
  },
  {
    id: '3-0-2',
    phase: '3-0-2',
    titre: 'dataloader',
    metaDescription: 'config',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9797891699743272',
    url: 'tag',
  },
  {
    id: '3-1-3',
    phase: '3-0-3',
    titre: 'train loop',
    metaDescription: 'config',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9797891699743272',
    url: 'tag',
  },
  {
    id: '4-0-0',
    phase: 'PHASE 4',
    titre: 'FRONTEND',
    metaDescription: 'init src css ascii js json',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '4081978916997932982',
    url: 'tag',
  },
  {
    id: '4-0-1',
    phase: '4-0-1',
    titre: 'html',
    metaDescription: 'index env-devops frontend',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '40819789169979397098',
    url: 'index.html',
  },
  {
    id: '4-0-2',
    phase: '4-0-2',
    titre: 'css',
    metaDescription: 'layout selected cell-ia',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '40819789197132982',
    url: 'css/style.css',
  },
  {
    id: '4-0-3',
    phase: '4-0-3',
    titre: 'javascript',
    metaDescription: 'layout selected cell-ia',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '40819789197132982',
    url: 'js/script.js js/main.js',
  },
  {
    id: '4-0-4',
    phase: '4-0-4',
    titre: 'json',
    metaDescription: 'sql',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '408197891971378969',
    url: 'json/sciptMain.json',
  },
  {
    id: '5-0-0',
    phase: 'PHASE 5',
    titre: 'BACKEND',
    metaDescription: 'init db_table js json  sql',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '408197891699799077',
    url: 'srv',
  },
  {
    id: '5-0-1',
    phase: '5-0-1',
    titre: 'backend',
    metaDescription: 'init db_table js json  sql',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '408197891699799077',
    url: 'srv',
  },
  {
    id: '5-0-2',
    phase: '5-0-2',
    titre: 'backend',
    metaDescription: 'init db_table js json  sql',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '408197891699799077',
    url: 'srv/server.js',
  },
  {
    id: '5-0-3',
    phase: '5-0-3',
    titre: 'backend',
    metaDescription: 'init db_table js json  sql',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '408197891699799077',
    url: 'srv/db_table.js srv/db-table.json',
  },
  {
    id: '6-0-0',
    phase: 'PHASE 6',
    titre: 'TEST NORME',
    metaDescription: 'dev output name fetch post w3c if true valided',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '60182789169787696',
    url: 'w3c',
  },
  {
    id: '7-0-0',
    phase: 'PHASE 7',
    titre: 'DevOps Plan',
    metaDescription: 'dev output name fetch post w3c if true valided',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9070827891697890709',
    url: 'devops',
  },
  {
    id: '8-0-0',
    phase: 'PHASE 8',
    titre: 'COM strategy',
    metaDescription: 'backend github univers-mc',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9808278916978986698',
    url: 'commit upade',
  },
  {
    id: '9-0-0',
    phase: 'PHASE 9',
    titre: 'SAVE DEPLOYMENT',
    metaDescription: 'backend github univers-mc',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9808278916978986698',
    url: 'commit upade',
  },
  {
    id: '1-1-0',
    phase: 'PHASE 10',
    titre: 'SAVE DEPLOYMENT',
    metaDescription: 'backend github univers-mc',
    startDate: '2024-02-01',
    duration:'5m',
    endDate: '2024-02-15',
    progress: '30%',
    promptModel:'x',
    promptNeofs:'x',
    promptZira:'x',
    currentStep:'work fonction',
    step1:'3%',
    step2:'10%',
    step3: '2%',
    step4: '3%',
    step5: '7%',
    apiRrest: 'email',
    hash: '9808278916978986698',
    url: 'loops return request rendu',
  },
  // Ajoutez d'autres tâches selon vos besoins
];
tasks.forEach((task) => {
  const row = document.createElement('tr');
  Object.values(task).forEach((value) => {
    const td = document.createElement('td');
    td.textContent = value;
    row.appendChild(td);
  });
  tbody.appendChild(row);
});

// Ajoutez l'en-tête et le corps à la table
table.appendChild(thead);
table.appendChild(tbody);

// Ajoutez la table de Gantt au conteneur
ganttContainer.appendChild(table);
